### ISSUE TITLE
Job `state` and `type` parameter and descriptions should be cleaner

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/vulmatch#16]
![image](https://github.com/user-attachments/assets/26b54213-67a8-460c-98cd-0e5bcf3b9ded)

The dropdown already contains all the options, so we don't need to print these in the parameter description.

For:

`state`: Filter the results by the state of the Job
`type`: Filter the results by the type of Job

**Comment by fqrious** [comment]
1. I'm not the one printing it, that's how the schema generator works
2. Okay
