### ISSUE TITLE
Make Arango CTI Processor jobs automatic

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/vulmatch#2]
Currently use triggers job manually

```
/api/v1/arango-cti-processor/{mode}/
```

However, we should trigger these based on downloads (e.g. CVE POST download, ATT&CK POST download), and remove this endpoint.

We should run the `mode`s of the download.

e.g. if user downloads ATT&CK, the following modes will run after the download

```
attack-capec, capec-attack, cve-attack
```

Note, to stop issues with jobs conflicting, only one download job (with Arango CTI Processor joins) should run at any time.

Lets say user runs download CVE and then immediately download ATT&CK, the ATT&CK job will be queued until the CVE download completes.

**Comment by olarid7852** [comment]
what arguments should they be run with?

**Comment by fqrious** [comment]
These tasks have arguments, so what arguments should they run with... Should it run as the same job or spawn another job?

**Comment by himynamesdave** [comment]
to me (although i'm not totally sure) it makes sense to separate jobs.

e.g. lets say i run 

```
GET /api/v1/cve/
```

to download CVES

this would mean the following ACTIP modes would need to be run: attack-capec, capec-attack, cve-attack

We could wrap each of these as a job (but could include them in the download job too). I'll let you decide.

The other point being (which might affect the decision) is that lets imagine a user runs 

```
GET /api/v1/cpe/
``` 

before the CVE tasks complete.

We should not start this job (and all ACTIP jobs) until the CVE one completes.

**Comment by himynamesdave** [comment]
@fqrious actually ignore this ticket for now. It makes more sense to add this logic (as a feature) to the Vulmatch web app.
