### ISSUE TITLE
Add DELETE endpoints

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/vulmatch#32]
should have DELETE endpoints

/api/v1/cve/ (Delete all CVE records // Use this endpoint to delete all CVE records)
/api/v1/cpe/ (Delete all CPE records // Use this endpoint to delete all CPE records)
/api/v1/attack-enterprise/ (Delete all ATT&CK Enterprise records // Use this endpoint to delete all ATT&CK Enterprise records)
/api/v1/attack-ics/ (Delete all ATT&CK ICS records // Use this endpoint to delete all ATT&CK ICS records)
/api/v1/attack-mobile/ (Delete all ATT&CK Mobile records // Use this endpoint to delete all ATT&CK Mobile records)
/api/v1/capec/ (Delete all CAPEC records // Use this endpoint to delete all CAPEC records)
/api/v1/cwe/ (Delete all CWE records // Use this endpoint to delete all CWE records)

This will be a crude delete, in that is will delete the edge/vertex collection for the specific data.

e.g. delete CVE will delete the CVE collections.

The point of these endpoints is mainly for testing. Right now I need to automate the delete of data to help me test cleanly

**Comment by fqrious** [comment]
if it's only needed for testing, it's better to just write it in the testing code...

**Comment by himynamesdave** [comment]
fair point. i'll do that.
